### ISSUE TITLE
Tela de tutorial - Atualizar o Logo

### ISSUE THREAD

**Issue by m-gomes** [CRUDParaSempre/DOCES#153]
Ao entrar na tela de tutorial deve atualizar o sprite do logo para o certo. A referencia para o logo escolhido pelo player está no game manager.

**Comment by guilhermeleobas** [comment]
@juniocezar @m-gomes No seu código, você colocou a parte de atualizar na função "update", e ela é chamada toda vez que atualiza o frame. Você poderia colocar no "start", visto que a logo não muda.

**Comment by juniocezar** [comment]
Movido
