### ISSUE TITLE
Tela Personagem - Procurar por falhas na tela de criação do personagem

### ISSUE THREAD

**Issue by m-gomes** [CRUDParaSempre/DOCES#175]
Listar todas as falhas encontradas na tela de criação do personagem.

**Comment by guilhermeleobas** [comment]
O usuário deve distribuir todos os pontos de habilidade ao criar o personagem. @m-gomes fez o pull request #197 que exibe um warning caso os pontos não tenham sido distribuídos. 

![image](https://cloud.githubusercontent.com/assets/2712115/20108039/de82bb70-a5c1-11e6-8b2d-8626f144c9e5.png)

**Comment by guilhermeleobas** [comment]
Bug: O usuário deve digitar um nome para o seu personagem. O pull request #198 resolve isso.

![image](https://cloud.githubusercontent.com/assets/2712115/20109055/932423ae-a5c5-11e6-9282-3c1d4bff8f19.png)
