### ISSUE TITLE
Tela Empresa - Procurar por falhas na tela de criação da empresa

### ISSUE THREAD

**Issue by m-gomes** [CRUDParaSempre/DOCES#176]
Listar todas as falhas encontradas na tela de criação da empresa.

**Comment by guilhermeleobas** [comment]
Bug: O usuário deve digitar o nome da empresa. Exibir um warning caso contrario. O pull request #198 resolve isso.

![image](https://cloud.githubusercontent.com/assets/2712115/20109412/14a6a626-a5c7-11e6-8722-bfccd69a5583.png)
