### ISSUE TITLE
Tela de início - Botão para Página do Projeto

### ISSUE THREAD

**Issue by m-gomes** [CRUDParaSempre/DOCES#30]
Sub-tarefa de #1
Este botão deve abrir uma aba no navegador para a página principal do nosso jogo.

**Comment by guilhermeleobas** [comment]
@m-gomes @marianaossilva 
Esse botão faz parte do dropdown menu?

**Comment by m-gomes** [comment]
A priori sim, mas isso não deve impactar na implementação dele. Implementa ele e cria um prefab (https://www.youtube.com/watch?v=HECGcwwRM64) do objeto final para que ele seja usado no DropdownMenu

**Comment by guilhermeleobas** [comment]
O dropdown precisa tá pronto antes de fazer o botão?

Upd: o botão para a página do projeto não faz parte do dropdown.
